import { DatabaseSync } from 'node:sqlite'
import { mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
const root=dirname(fileURLToPath(import.meta.url));const file=join(root,'data','kynex.sqlite');mkdirSync(dirname(file),{recursive:true});export const db=new DatabaseSync(file)
db.exec(`PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS datasets(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,source TEXT,created_at TEXT NOT NULL,row_count INTEGER DEFAULT 0,schema_version TEXT NOT NULL); CREATE TABLE IF NOT EXISTS records(id INTEGER PRIMARY KEY AUTOINCREMENT,dataset_id INTEGER,org TEXT,code TEXT NOT NULL,description TEXT NOT NULL,plant TEXT,event_year INTEGER,entity_key TEXT,status TEXT DEFAULT 'ingested',fingerprint_json TEXT,created_at TEXT NOT NULL,UNIQUE(dataset_id,code)); CREATE TABLE IF NOT EXISTS resolutions(request_id TEXT PRIMARY KEY,payload_json TEXT NOT NULL,status TEXT,created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS reviews(id INTEGER PRIMARY KEY AUTOINCREMENT,request_id TEXT NOT NULL,record_id INTEGER,status TEXT NOT NULL,priority TEXT DEFAULT 'normal',comments TEXT,required_role TEXT DEFAULT 'material_master_officer',assigned_to TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS policies(id INTEGER PRIMARY KEY AUTOINCREMENT,version TEXT UNIQUE NOT NULL,name TEXT NOT NULL,rules_json TEXT NOT NULL,active INTEGER DEFAULT 0,created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,event TEXT NOT NULL,request_id TEXT,actor TEXT,action TEXT,details_json TEXT,created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS exports(id INTEGER PRIMARY KEY AUTOINCREMENT,dataset_id INTEGER,format TEXT NOT NULL,status TEXT NOT NULL,content TEXT NOT NULL,created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS passports(id INTEGER PRIMARY KEY AUTOINCREMENT,common_code TEXT UNIQUE NOT NULL,payload_json TEXT NOT NULL,qr_payload TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS benchmark_sets(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,source TEXT,created_at TEXT NOT NULL,row_count INTEGER DEFAULT 0,schema_version TEXT NOT NULL); CREATE TABLE IF NOT EXISTS benchmark_rows(id INTEGER PRIMARY KEY AUTOINCREMENT,set_id INTEGER NOT NULL,row_key TEXT NOT NULL,query TEXT NOT NULL,expected_code TEXT,label TEXT,plant TEXT,event_year INTEGER,entity_key TEXT,split TEXT,metadata_json TEXT,UNIQUE(set_id,row_key)); CREATE TABLE IF NOT EXISTS measurements(id INTEGER PRIMARY KEY AUTOINCREMENT,metric_id TEXT NOT NULL,dataset_tier TEXT NOT NULL,value REAL NOT NULL,unit TEXT NOT NULL,baseline REAL,cohort TEXT,source TEXT NOT NULL,status TEXT NOT NULL,actor TEXT NOT NULL,created_at TEXT NOT NULL);`)
const now=()=>new Date().toISOString();const stmt=(sql)=>db.prepare(sql)
export function createDataset(name,source,rowCount){const r=stmt('INSERT INTO datasets(name,source,created_at,row_count,schema_version) VALUES(?,?,?,?,?)').run(name,source,now(),rowCount,'kynex-material-v1');return Number(r.lastInsertRowid)}
export function insertRecords(datasetId,records){const q=stmt('INSERT OR REPLACE INTO records(dataset_id,org,code,description,plant,event_year,entity_key,fingerprint_json,created_at) VALUES(?,?,?,?,?,?,?,?,?)');for(const x of records)q.run(datasetId,x.org||'',x.code,x.description,x.plant||'',Number(x.event_year)||null,x.entity_key||'',x.fingerprint_json||'',now())}
export function createResolution(payload){stmt('INSERT OR REPLACE INTO resolutions(request_id,payload_json,status,created_at) VALUES(?,?,?,?)').run(payload.requestId,JSON.stringify(payload),payload.status,payload.createdAt||now())}
export function createReview(requestId,recordId,status='pending',priority='normal',comments=''){const t=now();const r=stmt('INSERT INTO reviews(request_id,record_id,status,priority,comments,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(requestId,recordId,status,priority,comments,t,t);return Number(r.lastInsertRowid)}
export function listReviews(){return stmt("SELECT * FROM reviews ORDER BY CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 ELSE 2 END,updated_at DESC").all()}
export function updateReview(id,status,comments,actor){stmt('UPDATE reviews SET status=?,comments=?,assigned_to=?,updated_at=? WHERE id=?').run(status,comments||'',actor||'',now(),id);addAudit({event:'review_decision',action:status,actor,details:{reviewId:id,comments}});return stmt('SELECT * FROM reviews WHERE id=?').get(id)}
export function listPolicies(){return stmt('SELECT * FROM policies ORDER BY active DESC,created_at DESC').all()}
export function seedPolicy(){if(Number(stmt('SELECT COUNT(*) AS n FROM policies').get().n)===0)stmt('INSERT INTO policies(version,name,rules_json,active,created_at) VALUES(?,?,?,?,?)').run('1.0.0','Material identity safety policy',JSON.stringify({criticalFields:['pressureClass','material','nominalDiameterMm','type'],autoPublish:false,dualApprovalForCritical:true,abstainMargin:8}),1,now())}
export function addAudit({event,requestId='',actor='system',action='',details={}}){stmt('INSERT INTO audit(event,request_id,actor,action,details_json,created_at) VALUES(?,?,?,?,?,?)').run(event,requestId,actor,action,JSON.stringify(details),now())}
export function listAudit(){return stmt('SELECT * FROM audit ORDER BY id DESC LIMIT 250').all()}
export function createExport(datasetId,content,format='csv'){const r=stmt('INSERT INTO exports(dataset_id,format,status,content,created_at) VALUES(?,?,?,?,?)').run(datasetId,format,'ready',content,now());addAudit({event:'export_created',action:'export_only',details:{exportId:Number(r.lastInsertRowid),datasetId,format}});return {id:Number(r.lastInsertRowid),format,status:'ready',content}}
export function createPassport(commonCode,payload,status='certified'){const qrPayload=`https://kynex.local/passports/${encodeURIComponent(commonCode)}`;stmt('INSERT OR REPLACE INTO passports(common_code,payload_json,qr_payload,status,created_at) VALUES(?,?,?,?,?)').run(commonCode,JSON.stringify(payload),qrPayload,status,now());return {commonCode,qrPayload,status,payload}}
export function createBenchmarkSet(name,source,rowCount){const r=stmt('INSERT INTO benchmark_sets(name,source,created_at,row_count,schema_version) VALUES(?,?,?,?,?)').run(name,source,now(),rowCount,'kynex-benchmark-v1');return Number(r.lastInsertRowid)}
export function insertBenchmarkRows(setId,rows){const q=stmt('INSERT OR REPLACE INTO benchmark_rows(set_id,row_key,query,expected_code,label,plant,event_year,entity_key,split,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?)');for(const x of rows)q.run(setId,x.row_key||x.id||`row-${Math.random().toString(36).slice(2)}`,x.query||x.description||'',x.expected_code||x.expected||'',x.label||'',x.plant||'',Number(x.event_year||x.year)||null,x.entity_key||x.entity||'',x.split||'',JSON.stringify(x))}
export function listBenchmarkSets(){return stmt('SELECT * FROM benchmark_sets ORDER BY id DESC').all()}
export function getBenchmarkRows(setId){return stmt('SELECT * FROM benchmark_rows WHERE set_id=? ORDER BY id').all(setId)}
export function getPassport(commonCode){const x=stmt('SELECT * FROM passports WHERE common_code=?').get(commonCode);return x?{...x,payload:JSON.parse(x.payload_json)}:null}
export function createMeasurement({metricId,datasetTier,value,unit,baseline=null,cohort='',source,status='recorded',actor='system'}){const r=stmt('INSERT INTO measurements(metric_id,dataset_tier,value,unit,baseline,cohort,source,status,actor,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(metricId,datasetTier,Number(value),unit,baseline===null?null:Number(baseline),cohort,source,status,actor,now());return stmt('SELECT * FROM measurements WHERE id=?').get(Number(r.lastInsertRowid))}
export function listMeasurements(){return stmt('SELECT * FROM measurements ORDER BY id DESC LIMIT 500').all()}
seedPolicy()
