import { readFileSync } from 'node:fs'
const standardsRegistry=JSON.parse(readFileSync(new URL('./data/standards.json',import.meta.url),'utf8'))
const synonyms = new Map([['valve','valve'],['vlv','valve'],['gate','gate'],['gates','gate'],['ss','stainless'],['ss316','stainless'],['cf8m','stainless'],['stainless','stainless'],['flg','flanged'],['flange','flanged'],['flanged','flanged'],['ea','each'],['each','each'],['nos','each'],['pcs','each'],['bolt','bolt'],['fastener','fastener'],['impeller','impeller'],['pump','pump'],['pn16','pn16'],['pn25','pn25'],['pn40','pn40']])
export const criticalFields = ['pressureClass','material','nominalDiameterMm','type']
export const candidates = [
  { id:'CPCL-VLV-04182', org:'CPCL', code:'CPCL-VLV-04182', description:'SS GATE VALVE 2 IN PN16 FLG', plant:'Manali Refinery', eventYear:2025, entityKey:'gate-valve-ss50-pn16', category:'valve', type:'gate', material:'stainless', nominalDiameterMm:50, pressureClass:'PN16', connection:'flanged', uom:'each', commonCode:'CNMC-VALVE-GATE-SS-050-PN16' },
  { id:'SAIL-VALVE-G50-16', org:'SAIL', code:'SAIL-VALVE-G50-16', description:'GATE VLV SS316 DN50 PN16 FLANGED', plant:'Bhilai Steel Plant', eventYear:2025, entityKey:'gate-valve-ss50-pn16', category:'valve', type:'gate', material:'stainless', nominalDiameterMm:50, pressureClass:'PN16', connection:'flanged', uom:'each', commonCode:'CNMC-VALVE-GATE-SS-050-PN16' },
  { id:'NTPC-VLV-3307', org:'NTPC', code:'NTPC-VLV-3307', description:'VALVE GATE 50MM SS PN25 FLG', plant:'Ramagundam STPS', eventYear:2024, entityKey:'gate-valve-ss50-pn25', category:'valve', type:'gate', material:'stainless', nominalDiameterMm:50, pressureClass:'PN25', connection:'flanged', uom:'each', commonCode:'CNMC-VALVE-GATE-SS-050-PN25' },
  { id:'IOCL-VLV-2201', org:'IOCL', code:'IOCL-VLV-2201', description:'CARBON STEEL GATE VALVE DN50 PN16', plant:'Panipat Refinery', eventYear:2023, entityKey:'gate-valve-cs50-pn16', category:'valve', type:'gate', material:'carbon steel', nominalDiameterMm:50, pressureClass:'PN16', connection:'flanged', uom:'each', commonCode:'CNMC-VALVE-GATE-CS-050-PN16' },
  { id:'BPCL-BLT-M10-50', org:'BPCL', code:'BPCL-BLT-M10-50', description:'SS HEX BOLT M10 X 50 MM', plant:'Mumbai Refinery', eventYear:2025, entityKey:'bolt-ss-m10-50', category:'fastener', type:'bolt', material:'stainless', nominalDiameterMm:10, pressureClass:null, connection:'threaded', uom:'each', commonCode:'CNMC-FASTENER-BOLT-SS-M10-050' },
  { id:'HPCL-IMP-200', org:'HPCL', code:'HPCL-IMP-200', description:'SS316 CLOSED PUMP IMPELLER 200MM', plant:'Visakh Refinery', eventYear:2022, entityKey:'impeller-ss200', category:'pump', type:'impeller', material:'stainless', nominalDiameterMm:200, pressureClass:null, connection:null, uom:'each', commonCode:'CNMC-PUMP-IMPELLER-SS-200' }
]

function normalizeToken(value){const token=String(value||'').toLowerCase().replace(/[^a-z0-9.]+/g,'');return synonyms.get(token)||token}
export function tokenSet(text){return new Set(String(text||'').toLowerCase().split(/[^a-z0-9.]+/).filter(Boolean).map(normalizeToken))}
export function lexicalScore(a,b){const left=tokenSet(a),right=tokenSet(b),intersection=[...left].filter(x=>right.has(x)).length,union=new Set([...left,...right]).size||1;return Number((intersection/union*100).toFixed(1))}
export function extractFingerprint(input){const raw=[input.rawDescription,input.description,input.name].filter(Boolean).join(' '),lower=raw.toLowerCase(),explicit=input.attributes||{};const boltSizeMatch=lower.match(/\bm\s*(\d+(?:\.\d+)?)/);const diameterMatch=/\bbolt\b|\bhex\b/.test(lower)&&boltSizeMatch?boltSizeMatch:(lower.match(/(?:dn\s*)?(\d+(?:\.\d+)?)\s*(?:in(?:ch)?|\")/)||lower.match(/(?:dn\s*)?(\d+(?:\.\d+)?)\s*mm/)||lower.match(/dn\s*(\d+)/));const inches=/(?:in|inch|\")/.test(diameterMatch?.[0]||'');const diameterRaw=diameterMatch?Number(diameterMatch[1]):Number(explicit.nominalDiameter||0)||null;const diameterMm=diameterRaw?(inches?Number((diameterRaw*25.4).toFixed(1)):diameterRaw):null;const pressure=(lower.match(/pn\s*\d+/i)?.[0]||explicit.pressureClass||'').replace(/\s/g,'').toUpperCase()||null;const material=/cf8m|ss316|\bss\b|stainless/.test(lower)?'stainless':/carbon\s*steel|\bcs\b/.test(lower)?'carbon steel':(explicit.material||null);const type=/gate/.test(lower)?'gate':/bolt/.test(lower)?'bolt':/impeller/.test(lower)?'impeller':/ball/.test(lower)?'ball':/globe/.test(lower)?'globe':explicit.type||null;const category=/valve|vlv/.test(lower)?'valve':/bolt|fastener/.test(lower)?'fastener':/impeller|pump/.test(lower)?'pump':explicit.category||null;const connection=/flg|flange|flanged/.test(lower)?'flanged':/thread|screwed/.test(lower)?'threaded':explicit.connection||null;const uom=/\b(ea|each|nos|pcs)\b/.test(lower)?'each':explicit.uom||'each';const normalizedDiameter=diameterMm?(diameterMm>=49&&diameterMm<=52?50:diameterMm):null;return {rawDescription:raw,category,type,material,nominalDiameterMm:normalizedDiameter,nominalDiameterRaw:diameterRaw,nominalDiameterUnit:inches?'inch':diameterMatch?'mm':null,pressureClass:pressure,connection,uom,extractionConfidence:Number(([category,type,material,normalizedDiameter,pressure].filter(Boolean).length/5*100).toFixed(1)),normalizationNotes:[diameterMm&&inches?`${diameterRaw} in → ${diameterMm} mm → nominal DN${normalizedDiameter}`:null,material==='stainless'?'SS / SS316 / CF8M mapped to stainless material family':null,connection==='flanged'?'FLG / flange / flanged mapped to flanged connection':null].filter(Boolean)}}
function fieldScore(field,q,c){const a=q[field],b=c[field];if(a==null||b==null)return {score:null,state:'missing'};if(field==='nominalDiameterMm'){const delta=Math.abs(Number(a)-Number(b));return {score:delta===0?100:delta<=1?92:Math.max(0,100-delta*4),state:delta===0?'match':'mismatch'}};return {score:a===b?100:field==='material'&&a==='stainless'&&b==='carbon steel'?15:0,state:a===b?'match':'mismatch'}}
function scoreCandidate(fingerprint,candidate){const fields=['category','type','material','nominalDiameterMm','pressureClass','connection','uom'],scores=Object.fromEntries(fields.map(field=>[field,fieldScore(field,fingerprint,candidate)])),available=fields.filter(field=>scores[field].score!==null),attributeScore=available.length?available.reduce((sum,field)=>sum+scores[field].score,0)/available.length:0,conflicts=criticalFields.filter(field=>scores[field].state==='mismatch').map(field=>({field,query:fingerprint[field],candidate:candidate[field]})),lexical=lexicalScore(fingerprint.rawDescription,candidate.description),taxonomy=scores.category.score===100&&scores.type.score===100?100:scores.category.score===100||scores.type.score===100?70:0,unit=scores.uom.score==null?60:scores.uom.score,hardConflict=conflicts.some(c=>['pressureClass','material','nominalDiameterMm'].includes(c.field)),composite=Number(Math.max(0,lexical*.28+attributeScore*.52+taxonomy*.12+unit*.08-(hardConflict?22:0)).toFixed(1));return {candidate,scores,lexical,taxonomy,unit,attributeScore:Number(attributeScore.toFixed(1)),composite,conflicts,hardConflict}}

const trainingRows=[['SS GATE VALVE 2 IN PN16 FLG','CPCL-VLV-04182',1],['GATE VLV SS316 DN50 PN16 FLANGED','SAIL-VALVE-G50-16',1],['VALVE GATE 50MM SS PN25 FLG','NTPC-VLV-3307',1],['CARBON STEEL GATE VALVE DN50 PN16','IOCL-VLV-2201',1],['SS HEX BOLT M10 X 50 MM','BPCL-BLT-M10-50',1],['SS316 CLOSED PUMP IMPELLER 200MM','HPCL-IMP-200',1]]
let mlWeights=[-1.4,2.1,2.4,1.2,-2.5,-1.1]
function mlFeatures(fingerprint,item){const s=scoreCandidate(fingerprint,item);return [1,s.lexical/100,s.attributeScore/100,s.taxonomy/100,s.conflicts.length?1:0,s.hardConflict?1:0]}
function trainReranker(){for(let epoch=0;epoch<90;epoch++){for(const [query,id,label] of trainingRows){const fp=extractFingerprint({rawDescription:query}),rows=candidates.map(c=>({c,x:mlFeatures(fp,c)}));for(const row of rows){const y=row.c.id===id?label:0,logit=mlWeights.reduce((a,w,i)=>a+w*row.x[i],0),p=1/(1+Math.exp(-logit)),lr=.08;mlWeights=mlWeights.map((w,i)=>w+lr*(y-p)*row.x[i])}}}return mlWeights}
trainReranker()
function calibrateScore(score){const bounded=Math.min(99.9,Math.max(.1,Number(score)));const logit=Math.log(bounded/(100-bounded));return Number((1/(1+Math.exp(-logit/1.25))*100).toFixed(1))}
function rankWithMode(fingerprint,mode){const scored=candidates.map(c=>{const s=scoreCandidate(fingerprint,c);const exact=tokenSet(fingerprint.rawDescription).size&&tokenSet(fingerprint.rawDescription).size===tokenSet(c.description).size&&[...tokenSet(fingerprint.rawDescription)].every(t=>tokenSet(c.description).has(t));const ml=mlWeights.reduce((sum,w,i)=>sum+w*mlFeatures(fingerprint,c)[i],0);const rawMl=Number((1/(1+Math.exp(-ml))*100).toFixed(1));return {...s,exact:Boolean(exact),ml:rawMl,mlCalibrated:calibrateScore(rawMl)}});return scored.sort((a,b)=>mode==='exact'?Number(b.exact)-Number(a.exact)||b.lexical-a.lexical:mode==='fuzzy'?b.lexical-a.lexical:mode==='ml'?b.ml-a.ml:b.composite-a.composite)}
function decisionProfile(top,{abstain,missingCritical}){if(top.hardConflict)return {classKey:'unsafe_similarity',label:'Unsafe similarity',risk:'critical',nextAction:'DO_NOT_MERGE',explanation:'Critical technical attributes conflict; similarity cannot establish interchangeability'};if(abstain||missingCritical.length)return {classKey:'evidence_incomplete',label:'Evidence incomplete',risk:'high',nextAction:'REQUEST_CLARIFICATION',explanation:'Required evidence is missing or too close to safely classify'};if(top.composite>=96&&top.attributeScore>=90)return {classKey:'exact_identity',label:'Exact identity candidate',risk:'low',nextAction:'EXPERT_APPROVAL',explanation:'Typed attributes and normalized description strongly agree'};return {classKey:'functional_equivalence',label:'Functional equivalence candidate',risk:'medium',nextAction:'EXPERT_APPROVAL',explanation:'The material family and function align, but substitution requires expert approval'}}
function standardsContext(fingerprint){const records=standardsRegistry.filter(x=>x.family===fingerprint.category);return {category:fingerprint.category||'unclassified',references:records.map(x=>x.title),records,registryVersion:'2026.09',status:'REFERENCE_CONTEXT_ONLY',note:'Standards applicability must be verified by the responsible engineer before approval'}}
export function resolveMaterial(payload,{mode='rules'}={}){const fingerprint=extractFingerprint(payload),scored=rankWithMode(fingerprint,mode),top=scored[0],second=scored[1],margin=Number((top.composite-second.composite).toFixed(1)),missingCritical=criticalFields.filter(field=>fingerprint[field]==null),abstain=top.hardConflict||top.composite<78||margin<8||missingCritical.length>=2,profile=decisionProfile(top,{abstain,missingCritical}),classification=profile.classKey==='unsafe_similarity'?'conflict':profile.classKey==='evidence_incomplete'?'abstain':profile.classKey,reasons=[`Lexical evidence ${top.lexical}% after domain synonym expansion`,`Typed attribute agreement ${top.attributeScore}% across ${Object.values(top.scores).filter(x=>x.score!==null).length} available fields`,`Candidate margin ${margin} points over the next candidate`,...fingerprint.normalizationNotes,...top.conflicts.map(c=>`Conflict firewall: ${c.field} differs (${c.query||'missing'} vs ${c.candidate})`)];if(missingCritical.length)reasons.push(`Missing critical attributes: ${missingCritical.join(', ')}`);if(margin<8)reasons.push('Abstention rule: evidence is too close to safely recommend one identity');return {requestId:`RES-${Date.now().toString(36).toUpperCase()}`,createdAt:new Date().toISOString(),status:classification,decision:classification==='conflict'?'DO_NOT_MERGE':classification==='abstain'?'HUMAN_REVIEW_REQUIRED':'RECOMMEND_FOR_EXPERT_REVIEW',fingerprint,recommendation:{commonCode:top.candidate.commonCode,matchedRecord:top.candidate.code,confidence:top.composite,mlConfidence:top.mlCalibrated,margin,rationale:reasons},outcome:{...profile,approvedSubstitution:false},risk:{score:Number((profile.risk==='critical'?92:profile.risk==='high'?68:profile.risk==='medium'?38:12)+(top.hardConflict?8:0)),level:profile.risk,criticalAttributes:criticalFields,missingAttributes:missingCritical},standards:standardsContext(fingerprint),candidates:scored.map(item=>({id:item.candidate.id,org:item.candidate.org,code:item.candidate.code,description:item.candidate.description,commonCode:item.candidate.commonCode,plant:item.candidate.plant,composite:item.composite,lexical:item.lexical,attributeScore:item.attributeScore,ml:item.ml,conflicts:item.conflicts,relationship:item.hardConflict?'CONFLICT — DO NOT MERGE':item.composite>=96?'NEAR DUPLICATE':'POSSIBLE MATCH'})),controls:{conflictFirewall:top.hardConflict?'TRIGGERED':'CLEAR',abstention:abstain?'TRIGGERED':'CLEAR',autoPublish:false,legacyOverwrite:false,expertApprovalRequired:true},evidence:{lexical:top.lexical,attribute:top.attributeScore,taxonomy:top.taxonomy,unit:top.unit,margin,model:mode,reasons,sourceLineage:'retained native record → normalized fingerprint → candidate evidence'},retrieval:{topK:Math.min(5,scored.length),candidateCount:scored.length,returned:true}}
}

function binaryMetrics(actual,predicted){const tp=actual.filter((x,i)=>x&&predicted[i]).length,fp=actual.filter((x,i)=>!x&&predicted[i]).length,fn=actual.filter((x,i)=>x&&!predicted[i]).length,precision=tp/(tp+fp||1),recall=tp/(tp+fn||1),f1=2*precision*recall/(precision+recall||1);return {tp,fp,fn,precision:Number((precision*100).toFixed(1)),recall:Number((recall*100).toFixed(1)),f1:Number((f1*100).toFixed(1))}}
function classificationMetrics(rows){const decisions=rows.map(r=>resolveMaterial({rawDescription:r.query||r.description||''}));const actualConflict=rows.map(r=>['conflict','unsafe_similarity'].includes(r.label)),predictedConflict=decisions.map(r=>r.status==='conflict'),actualAbstain=rows.map(r=>['ambiguous','insufficient_evidence'].includes(r.label)||(!r.expected&&!['conflict','unsafe_similarity'].includes(r.label))),predictedAbstain=decisions.map(r=>r.status==='abstain');return {conflictDetection:binaryMetrics(actualConflict,predictedConflict),abstention:binaryMetrics(actualAbstain,predictedAbstain)}}
export function evaluateLabelledRows(rows,dataset='labelled benchmark upload'){const clean=rows.map((r,i)=>({id:r.id||r.row_key||`row-${i+1}`,query:r.query||r.description||'',expected:r.expected||r.expected_code||'',label:r.label||'',plant:r.plant||'',year:Number(r.year||r.event_year)||null,entity:r.entity||r.entity_key||'',split:r.split||''}));const eligible=clean.filter(r=>r.expected);const scoreMode=(mode,subset=clean)=>{const eligibleSubset=subset.filter(r=>r.expected),correct=eligibleSubset.filter(r=>topFor(r.query,mode).candidate.id===r.expected).length;return {correct,total:eligibleSubset.length,accuracy:Number((correct/(eligibleSubset.length||1)*100).toFixed(1))}};const decisionRows=clean.map(r=>resolveMaterial({rawDescription:r.query}));const safetyRows=clean.filter((r,i)=>!r.expected||r.label==='ambiguous'||r.label==='conflict'||r.label==='unsafe_similarity');const abstentions=safetyRows.filter((r)=>{const x=resolveMaterial({rawDescription:r.query});return x.status==='abstain'||x.status==='conflict'}).length;const splitNames=[...new Set(clean.map(r=>r.split).filter(Boolean))];const splitRows=splitNames.length?Object.fromEntries(splitNames.map(name=>[name,clean.filter(r=>r.split===name)])):{all:clean};const calibration=calibrationMetrics(clean);return {dataset,rows:clean.length,labels:[...new Set(clean.map(r=>r.label).filter(Boolean))],models:{exact:scoreMode('exact'),fuzzy:scoreMode('fuzzy'),rules:scoreMode('rules'),mlReranker:scoreMode('ml')},splits:Object.fromEntries(Object.entries(splitRows).map(([name,subset])=>[name,{rows:subset.length,eligible:subset.filter(r=>r.expected).length,rules:scoreMode('rules',subset),mlReranker:scoreMode('ml',subset)}])),calibration,retrieval:{top3Recall:Number((eligible.filter(r=>rankWithMode(extractFingerprint({rawDescription:r.query}),'rules').slice(0,3).some(x=>x.candidate.id===r.expected)).length/(eligible.length||1)*100).toFixed(1)),abstentionCapture:Number((abstentions/(safetyRows.length||1)*100).toFixed(1)),criticalConflictRate:Number((decisionRows.filter(r=>r.controls.conflictFirewall==='TRIGGERED').length/(clean.length||1)*100).toFixed(1))},safety:{ambiguousRows:clean.filter(r=>!r.expected||r.label==='ambiguous').length,conflictRows:clean.filter(r=>r.label==='conflict'||r.label==='unsafe_similarity').length,abstentions:decisionRows.filter(r=>r.status==='abstain'||r.status==='conflict').length},classification:classificationMetrics(clean),evaluationBoundary:{labelledRows:eligible.length,unlabelledRows:clean.length-eligible.length,percentageClaimsAllowed:eligible.length>0,groundTruthRequired:true}}}

export const benchmarkRows=[
 {id:'b001',query:'SS GATE VALVE 2 IN PN16 FLG',expected:'CPCL-VLV-04182',label:'exact_duplicate',plant:'Manali Refinery',year:2025,entity:'gate-valve-ss50-pn16'},
 {id:'b002',query:'GATE VLV SS316 DN50 PN16 FLANGED',expected:'SAIL-VALVE-G50-16',label:'near_duplicate',plant:'Bhilai Steel Plant',year:2025,entity:'gate-valve-ss50-pn16'},
 {id:'b003',query:'VALVE GATE 50MM SS PN25 FLG',expected:'NTPC-VLV-3307',label:'exact_duplicate',plant:'Ramagundam STPS',year:2024,entity:'gate-valve-ss50-pn25'},
 {id:'b004',query:'CARBON STEEL GATE VALVE DN50 PN16',expected:'IOCL-VLV-2201',label:'exact_duplicate',plant:'Panipat Refinery',year:2023,entity:'gate-valve-cs50-pn16'},
 {id:'b005',query:'SS GATE VALVE 2 IN PN18 FLG',expected:null,label:'ambiguous',plant:'Manali Refinery',year:2026,entity:'unseen-pressure'},
 {id:'b006',query:'SS HEX BOLT M10 X 50 MM',expected:'BPCL-BLT-M10-50',label:'exact_duplicate',plant:'Mumbai Refinery',year:2025,entity:'bolt-ss-m10-50'},
 {id:'b007',query:'STAINLESS STEEL WEDGE VALVE DN50 PN16',expected:'CPCL-VLV-04182',label:'functional_equivalent',plant:'Kochi Refinery',year:2026,entity:'unseen-plant-valve'},
 {id:'b008',query:'SS316 CLOSED PUMP IMPELLER 200MM',expected:'HPCL-IMP-200',label:'exact_duplicate',plant:'Visakh Refinery',year:2022,entity:'impeller-ss200'}
]
function topFor(query,mode){const fp=extractFingerprint({rawDescription:query});return rankWithMode(fp,mode)[0]}
function accuracy(rows,mode){let eligible=rows.filter(r=>r.expected),correct=eligible.filter(r=>topFor(r.query,mode).candidate.id===r.expected).length;return {correct,total:eligible.length,accuracy:Number((correct/(eligible.length||1)*100).toFixed(1))}}
function retrievalMetrics(rows){const eligible=rows.filter(r=>r.expected),hitAt3=eligible.filter(r=>rankWithMode(extractFingerprint({rawDescription:r.query}),'rules').slice(0,3).some(x=>x.candidate.id===r.expected)).length,decisionRows=rows.map(r=>resolveMaterial({rawDescription:r.query})),incompleteIndices=rows.map((r,i)=>r.expected?null:i).filter(i=>i!==null),abstained=incompleteIndices.filter(i=>['abstain','conflict'].includes(decisionRows[i].status)).length;return {top3Recall:Number((hitAt3/(eligible.length||1)*100).toFixed(1)),abstentionCapture:Number((abstained/(incompleteIndices.length||1)*100).toFixed(1)),criticalConflictRate:Number((decisionRows.filter(r=>r.controls.conflictFirewall==='TRIGGERED').length/(rows.length||1)*100).toFixed(1))}}
function calibrationMetrics(rows){const eligible=rows.filter(r=>r.expected),points=eligible.map(r=>{const top=topFor(r.query,'ml');return {confidence:top.mlCalibrated/100,correct:top.candidate.id===r.expected?1:0}}),brier=points.reduce((sum,p)=>sum+(p.confidence-p.correct)**2,0)/(points.length||1),bins=Array.from({length:5},(_,i)=>points.filter(p=>p.confidence>=i/5&&p.confidence<(i+1)/5)),ece=bins.reduce((sum,bin)=>{if(!bin.length)return sum;const avgConfidence=bin.reduce((s,p)=>s+p.confidence,0)/bin.length,avgAccuracy=bin.reduce((s,p)=>s+p.correct,0)/bin.length;return sum+(bin.length/points.length)*Math.abs(avgConfidence-avgAccuracy)},0);return {method:'temperature scaling',temperature:1.25,brierScore:Number(brier.toFixed(4)),expectedCalibrationError:Number(ece.toFixed(4)),evaluated:points.length}}
export function runBenchmark(){const splits={plant:benchmarkRows.filter(r=>r.plant==='Kochi Refinery'),time:benchmarkRows.filter(r=>r.year>=2026),unseenEntity:benchmarkRows.filter(r=>r.entity.startsWith('unseen'))};return {dataset:'KYNEX labelled resolution benchmark v1',rows:benchmarkRows.length,labels:[...new Set(benchmarkRows.map(r=>r.label))],models:{exact:accuracy(benchmarkRows,'exact'),fuzzy:accuracy(benchmarkRows,'fuzzy'),rules:accuracy(benchmarkRows,'rules'),mlReranker:accuracy(benchmarkRows,'ml')},splits:Object.fromEntries(Object.entries(splits).map(([name,rows])=>[name,{rows:rows.length,eligible:rows.filter(r=>r.expected).length,rules:accuracy(rows,'rules'),mlReranker:accuracy(rows,'ml')}])) ,calibration:calibrationMetrics(benchmarkRows),retrieval:retrievalMetrics(benchmarkRows),safety:{ambiguousRows:benchmarkRows.filter(r=>!r.expected).length,conflictRows:benchmarkRows.filter(r=>r.label==='conflict').length,abstentions:benchmarkRows.filter(r=>{const x=resolveMaterial({rawDescription:r.query});return x.status==='abstain'||x.status==='conflict'}).length},model:{type:'calibrated logistic reranker',features:['lexical overlap','typed attribute agreement','taxonomy alignment','critical conflict flag'],weights:mlWeights.map(x=>Number(x.toFixed(3))),note:'Model score is bounded by deterministic conflict and abstention gates'}}}
export function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'&&quoted&&next==='"'){cell+='"';i++;continue}if(ch==='"'){quoted=!quoted;continue}if(ch===','&&!quoted){row.push(cell.trim());cell='';continue}if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell='';continue}cell+=ch}if(cell||row.length){row.push(cell.trim());rows.push(row)}const headers=(rows.shift()||[]).map(h=>h.toLowerCase().replace(/\s+/g,'_'));return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]||''])))}
